### ISSUE TITLE
Tomcat fails to start

### ISSUE THREAD

**Issue by JoyceBabu** [valtri/docker-midpoint#1]
Tomcat is failing with the following message

```
2016-10-09 11:10:38,571 [] [localhost-startStop-1] WARN (org.apache.tomcat.util.scan.StandardJarScanner): Failed to scan [file:/usr/share/java/el-api-3.0.jar] from classloader hierarchy
java.io.FileNotFoundException: /usr/share/java/el-api-3.0.jar (No such file or directory)
    at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_102]
    at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:43) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:322) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:272) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1887) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1127) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:779) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:306) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5202) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-10-09 11:10:38,572 [] [localhost-startStop-1] WARN (org.apache.tomcat.util.scan.StandardJarScanner): Failed to scan [file:/usr/share/java/jsp-api-2.3.jar] from classloader hierarchy
java.io.FileNotFoundException: /usr/share/java/jsp-api-2.3.jar (No such file or directory)
    at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_102]
    at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:43) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:322) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:272) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:1887) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1127) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:779) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:306) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5202) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-10-09 11:10:39,039 [] [localhost-startStop-1] WARN (org.apache.tomcat.util.scan.StandardJarScanner): Failed to scan [file:/usr/share/java/el-api-3.0.jar] from classloader hierarchy
java.io.FileNotFoundException: /usr/share/java/el-api-3.0.jar (No such file or directory)
    at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_102]
    at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:43) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:322) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:272) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.jasper.servlet.TldScanner.scanJars(TldScanner.java:262) [tomcat8-jasper-8.0.36.jar:8.0.36]
    at org.apache.jasper.servlet.TldScanner.scan(TldScanner.java:106) [tomcat8-jasper-8.0.36.jar:8.0.36]
    at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:103) [tomcat8-jasper-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5292) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-10-09 11:10:39,040 [] [localhost-startStop-1] WARN (org.apache.tomcat.util.scan.StandardJarScanner): Failed to scan [file:/usr/share/java/jsp-api-2.3.jar] from classloader hierarchy
java.io.FileNotFoundException: /usr/share/java/jsp-api-2.3.jar (No such file or directory)
    at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_102]
    at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_102]
    at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_102]
    at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:43) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:322) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:272) ~[tomcat8-util-scan-8.0.36.jar:8.0.36]
    at org.apache.jasper.servlet.TldScanner.scanJars(TldScanner.java:262) [tomcat8-jasper-8.0.36.jar:8.0.36]
    at org.apache.jasper.servlet.TldScanner.scan(TldScanner.java:106) [tomcat8-jasper-8.0.36.jar:8.0.36]
    at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:103) [tomcat8-jasper-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5292) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834) [tomcat8-catalina-8.0.36.jar:8.0.36]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016-10-09 11:10:39,041 [] [localhost-startStop-1] INFO (org.apache.jasper.servlet.TldScanner): At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
```

I could find `jsp-api.jar` and `el-api.jar` under `/usr/share/tomcat8/lib/`. Is that the new location of the files? If so, where should I update the path?

**Comment by valtri** [comment]
Yes, these are symlinks to jar files from other packages, but these dependencies are missing in tomcat8 package in Debian 9/stretch. It works fine though - starting script fails, but tomcat8 is started.

I've added the missing dependencies. Starting script still fails, but there are no errors in log file anymore.
